name: Sunwoo Github Action

on:
   push:
      branches:
         - main

jobs:
   assignment_4:
      name: 4주차 과제
      runs-on: ubuntu-latest
      steps: 
         - name: 레포 체크아웃
           uses: actions/checkout@v3

         - name: shell 실행
           shell: bash
           run: |
              cd scripts
              chmod +x hello.sh
              ./hello.sh

         - name: issue 생성
           uses: actions/github-script@v6
           with:
              script: |
                 github.rest.issues.createComment({
                 issue_number: context.issue.number,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 body: '감사합니다'
               })
