name: Sunwoo Github Action

on:
   push:
      branches:
         - main
         - 'Sunwoo0110-github-action'

jobs:
   assignment_4:
      name: 4주차 과제
      runs-on: ubuntu-latest
      steps:               
         - name: 레포 체크아웃
           uses: actions/checkout@v3

         - name: shell 실행
           shell: bash
           run: |
              cd scripts
              chmod +x hello.sh
              ./hello.sh


         - name: python 실행
           shell: python
           run: |
              import os
              print("파이썬 실행")
